import React from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useDemo } from '../data/DemoContext.jsx'
import { CandidateStatusBadge, Badge } from '../components/StatusBadge.jsx'

export default function AdminTriage() {
  const { missionId } = useParams()
  const navigate = useNavigate()
  const { candidates, triageShortlist, triageSuspend, createValidationMission, getIdeationMission } = useDemo()
  const mission = getIdeationMission(missionId)

  const pool = candidates.filter((c) => c.parentMissionId === missionId)

  function handleCreateMission(candidateId) {
    const vmId = createValidationMission(candidateId)
    navigate(`/validation/${vmId}`)
  }

  if (!mission) return <div className="card p-6 text-sm text-ink-500">Mission not found.</div>

  return (
    <div className="space-y-6">
      <div>
        <Badge tone="brand">Ideation triage</Badge>
        <h1 className="mt-2 text-xl font-semibold text-ink-900">{mission.title}</h1>
        <p className="mt-2 max-w-2xl text-sm text-ink-600">{mission.prompt}</p>
      </div>

      <p className="text-sm text-ink-500">
        {pool.length} Candidate{pool.length !== 1 && 's'} generated by Scouts. Merge duplicates, mark irrelevant
        ideas Suspended, and shortlist a manageable subset (illustratively 3–5) for validation.
      </p>

      <div className="grid gap-4 md:grid-cols-2">
        {pool.map((c) => (
          <div key={c.id} className="card p-4">
            <div className="mb-2 flex items-center justify-between">
              <span className="text-xs text-ink-400">{c.id}</span>
              <CandidateStatusBadge status={c.status} />
            </div>
            <div className="text-sm font-medium text-ink-900">{c.title}</div>
            <p className="mt-1 line-clamp-3 text-xs text-ink-500">{c.hypothesis}</p>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {c.tags.map((t) => (
                <span key={t} className="rounded-full bg-ink-100 px-2 py-0.5 text-xs text-ink-500">
                  #{t}
                </span>
              ))}
            </div>

            <div className="mt-4 flex flex-wrap gap-2">
              {c.status === 'Proposed' && (
                <>
                  <button className="btn-secondary text-xs" onClick={() => triageShortlist(c.id)}>
                    Shortlist
                  </button>
                  <button className="btn-secondary text-xs" onClick={() => triageSuspend(c.id)}>
                    Mark not selected
                  </button>
                  <button className="btn-secondary text-xs" disabled title="Demo: merge UI omitted for brevity">
                    Merge into…
                  </button>
                </>
              )}
              {c.status === 'Shortlisted' && !c.validationMissionId && (
                <button className="btn-primary text-xs" onClick={() => handleCreateMission(c.id)}>
                  Create Validation Mission
                </button>
              )}
              {c.validationMissionId && (
                <Badge tone="brand">Validation Mission {c.validationMissionId} created</Badge>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
